import { Client } from "../app/clients/_components/columns";

export async function fetchClients(): Promise<Client[]> {
  // simulate fetching data from an API with a delay
  return new Promise<Client[]>((resolve) => {
    setTimeout(() => {
      resolve([
        {
          id: "1",
          firstName: "Zach",
          lastName: "Olsen",
          email: "zach.olsen@example.com",
          leaseStartDate: new Date("2025-10-22"),
          leaseEndDate: new Date("2100-12-31"),
        },
        {
          id: "2",
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@example.com",
          leaseStartDate: new Date("2022-06-15"),
          leaseEndDate: new Date("2023-06-14"),
        },
        {
          id: "3",
          firstName: "Alice",
          lastName: "Johnson",
          email: "alice.johnson@example.com",
          leaseStartDate: new Date("2024-03-01"),
          leaseEndDate: new Date("2025-02-28"),
        },
        {
          id: "4",
          firstName: "Bob",
          lastName: "Lee",
          email: "bob.lee@example.com",
          leaseStartDate: new Date("2023-09-01"),
          leaseEndDate: new Date("2024-08-31"),
        },
        {
          id: "5",
          firstName: "Maria",
          lastName: "Garcia",
          email: "maria.garcia@example.com",
          leaseStartDate: new Date("2025-01-01"),
          leaseEndDate: new Date("2025-12-31"),
        },
        {
          id: "6",
          firstName: "David",
          lastName: "Kim",
          email: "david.kim@example.com",
          leaseStartDate: new Date("2023-05-10"),
          leaseEndDate: new Date("2024-05-09"),
        },
        {
          id: "7",
          firstName: "Emma",
          lastName: "Brown",
          email: "emma.brown@example.com",
          leaseStartDate: new Date("2022-11-01"),
          leaseEndDate: new Date("2023-10-31"),
        },
        {
          id: "8",
          firstName: "Liam",
          lastName: "Wilson",
          email: "liam.wilson@example.com",
          leaseStartDate: new Date("2024-07-01"),
          leaseEndDate: new Date("2025-06-30"),
        },
        {
          id: "9",
          firstName: "Olivia",
          lastName: "Martinez",
          email: "olivia.martinez@example.com",
          leaseStartDate: new Date("2023-03-15"),
          leaseEndDate: new Date("2024-03-14"),
        },
        {
          id: "10",
          firstName: "Noah",
          lastName: "Anderson",
          email: "noah.anderson@example.com",
          leaseStartDate: new Date("2022-08-01"),
          leaseEndDate: new Date("2023-07-31"),
        },
        {
          id: "11",
          firstName: "Sophia",
          lastName: "Thomas",
          email: "sophia.thomas@example.com",
          leaseStartDate: new Date("2024-02-01"),
          leaseEndDate: new Date("2025-01-31"),
        },
        {
          id: "12",
          firstName: "James",
          lastName: "Taylor",
          email: "james.taylor@example.com",
          leaseStartDate: new Date("2023-04-01"),
          leaseEndDate: new Date("2024-03-31"),
        },
        {
          id: "13",
          firstName: "Isabella",
          lastName: "Moore",
          email: "isabella.moore@example.com",
          leaseStartDate: new Date("2022-09-01"),
          leaseEndDate: new Date("2023-08-31"),
        },
        {
          id: "14",
          firstName: "Benjamin",
          lastName: "Jackson",
          email: "benjamin.jackson@example.com",
          leaseStartDate: new Date("2024-05-01"),
          leaseEndDate: new Date("2025-04-30"),
        },
        {
          id: "15",
          firstName: "Mia",
          lastName: "Martin",
          email: "mia.martin@example.com",
          leaseStartDate: new Date("2023-06-01"),
          leaseEndDate: new Date("2024-05-31"),
        },
        {
          id: "16",
          firstName: "Elijah",
          lastName: "White",
          email: "elijah.white@example.com",
          leaseStartDate: new Date("2022-10-01"),
          leaseEndDate: new Date("2023-09-30"),
        },
        {
          id: "17",
          firstName: "Charlotte",
          lastName: "Harris",
          email: "charlotte.harris@example.com",
          leaseStartDate: new Date("2024-08-01"),
          leaseEndDate: new Date("2025-07-31"),
        },
        {
          id: "18",
          firstName: "William",
          lastName: "Clark",
          email: "william.clark@example.com",
          leaseStartDate: new Date("2023-02-01"),
          leaseEndDate: new Date("2024-01-31"),
        },
        {
          id: "19",
          firstName: "Amelia",
          lastName: "Lewis",
          email: "amelia.lewis@example.com",
          leaseStartDate: new Date("2022-12-01"),
          leaseEndDate: new Date("2023-11-30"),
        },
        {
          id: "20",
          firstName: "Henry",
          lastName: "Walker",
          email: "henry.walker@example.com",
          leaseStartDate: new Date("2024-04-01"),
          leaseEndDate: new Date("2025-03-31"),
        },
        {
          id: "21",
          firstName: "Evelyn",
          lastName: "Hall",
          email: "evelyn.hall@example.com",
          leaseStartDate: new Date("2023-07-01"),
          leaseEndDate: new Date("2024-06-30"),
        },
        {
          id: "22",
          firstName: "Alexander",
          lastName: "Allen",
          email: "alexander.allen@example.com",
          leaseStartDate: new Date("2022-05-01"),
          leaseEndDate: new Date("2023-04-30"),
        },
        {
          id: "23",
          firstName: "Harper",
          lastName: "Young",
          email: "harper.young@example.com",
          leaseStartDate: new Date("2024-06-01"),
          leaseEndDate: new Date("2025-05-31"),
        },
        {
          id: "24",
          firstName: "Jack",
          lastName: "King",
          email: "jack.king@example.com",
          leaseStartDate: new Date("2023-11-01"),
          leaseEndDate: new Date("2024-10-31"),
        },
        {
          id: "25",
          firstName: "Ella",
          lastName: "Wright",
          email: "ella.wright@example.com",
          leaseStartDate: new Date("2022-07-01"),
          leaseEndDate: new Date("2023-06-30"),
        },
      ]);
    }, 1000);
  });
}
