name: Frontend Successfully Builds

on:
  pull_request:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          # make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build
        run: npm run build
