name: Successfully Builds

on:
  pull_request:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          # make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build
        env:
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_APP_URL: ${{http://localhost:3000}}
        run: npm run build
