name: Successfully Builds

on:
  pull_request:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          # make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Generate Prisma client
        env:
<<<<<<< HEAD
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: bunx prisma generate
=======
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          DIRECT_URL: ${{ vars.DIRECT_URL }}
        run: npx prisma generate
>>>>>>> origin

      - name: Build
        env:
          DIRECT_URL: ${{ vars.DIRECT_URL }}
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
        run: bun run build
